[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name="day-1"
path="src/day-1/main.rs"

[[bin]]
name="day-2"
path="src/day-2/main.rs"
[dependencies]
